The Game of Life is set in an infinite two-dimensional grid inhabited by “cells”. Every cell interacts with up to eight neighbours, which are the cells that are horizontally, vertically, or diagonally adjacent. 
From an initial seed grid the game "evolves" one iteration at a time. An iteration applies rules to the grid to determine its next state.

Below, I have created a function,'Neighbours', that will work inside my main function, 'Evolves'. I have also included some examples at the end of my code.

In [39]:
#Creating a starting array where '0' indicates an empty cell and '1' indicates a live cell.
import numpy as np
y = np.full((3,3),0)
#Adjusting the values of y depending on what we want our initial condition to be.
y[1][1]='1'
y[1][2]='1'
y[1][0]='1'
print(y)

[[0 0 0]
 [1 1 1]
 [0 0 0]]


In [40]:
#Creating z to allow us to test a random initial condition.
z=np.random.choice([0, 1], size=(10,10))
print(z)

[[0 1 0 0 0 0 0 1 0 0]
 [1 0 1 0 1 0 0 1 1 1]
 [1 0 0 0 1 0 0 0 1 1]
 [1 1 1 1 0 0 0 1 1 0]
 [0 0 1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 0 0 1]
 [0 1 1 1 0 1 1 0 0 1]
 [1 0 0 0 0 1 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 1]]


In [45]:
def Neighbours(y):
    #Creating a function that will count the neighbours of a cell and output the values into a matrix.
    
    height,width = y.shape #Defining the height and width of our y matrix
    
    #Creating a matrix that adds a border of one around our given y. This will help when we spiral round the cells.
    #First, create a matrix of zeros of size y, plus a border of one around the edge. Border values=0.
    Bordered_y = np.full((height+2,width+2),0)
    Bordered_y[1:height+1,1:width+1]=y #Set the interior region of our bordered matrix to be our matrix y.
    neighbourcount = np.full((height,width),0) #Setting an empty matrix for the counts to be added into.
    
    #Setting initial values
    minRow,minCol = 0,0
    maxRow,maxCol = 2,2
    rowVal,colVal = 0,0
    
    #Spiralling round the neighbours of each cell..
    for i in range(4):
        while colVal<maxCol: #moving right along top of spiral
            neighbourcount = neighbourcount + Bordered_y[rowVal:height+rowVal,colVal:width+colVal]
            colVal += 1

        while rowVal<maxRow: #moving down right hand side of spiral
            neighbourcount = neighbourcount + Bordered_y[rowVal:height+rowVal,colVal:width+colVal]
            rowVal += 1

        while colVal>minCol: #moving left along base of spiral
            neighbourcount = neighbourcount + Bordered_y[rowVal:height+rowVal,colVal:width+colVal]
            colVal -= 1
        minRow += 1
        maxCol -= 1
        while rowVal > minRow: #moving up left hand side of spiral
            neighbourcount = neighbourcount + Bordered_y[rowVal:height+rowVal,colVal:width+colVal]
            rowVal -= 1
        minCol += 1
        maxRow -= 1
    return neighbourcount #Returning a matrix with the corresponding neighbour count for each cell.

In [46]:
def Evolves(y,n): 
    #Creating a function that will grid the game "evolves" for our starting grid y and for n iterations.

    while n>0:
        neighbours=Neighbours(y) #Retrieving the neighbour counts for our grid
        
        #Scenario 0, No interactions - When there are no live cells, no live cells on next iteration too.
        if (y==0).all()==True: #If all the cells in y are dead (=0) then no live cells.
            y=y #Hence, no cells created. Grid remains unchanged.

        else:
            #Scenario 1, Underpopulation - When a live cell has fewer than two neighbours, this cell dies.
            for i in range(len(y)): #looking at the rows of y
                for j in range(len(y[i])): #looking at columns of y. (Working through each element of y)
                    if y[i][j]==1: #Looking at the live cells
                        if neighbours[i][j]<2:
                            y[i][j]=0
                            
                    #Scenario 2, Overcrowding - When a live cell has more than three neighbours, it dies.
                        if neighbours[i][j]>3:
                            y[i][j]=0
                            
                    #Scenario 3, Survival - When a live cell has two or three neighbours, it stays alive.
                    #Leaving cell as is.
                    
                    #Scenario 4, Creation of life - When an empty position has exactly three neighbouring cells, 
                    #then a cell is created in this position
                    else: #Looking at the empty cells
                        if neighbours[i][j]==3:
                            y[i][j]=1
        n=n-1 #Working through the iterations
    print(y)

In [47]:
#Testing to see if the function produces the desired outcome.
Evolves(y,3)

[[0 0 0]
 [1 1 1]
 [0 0 0]]


In [48]:
#Example of evolves on a random initial condition.
Evolves(z,100)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
